apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata: 
      labels:
        app: sample-application
    spec: 
      containers:
        - name: nodejs
          image: darwinwilmut/sample-application:22
          ports:
            - containerPort: 80
