apiVersion: apps/v1
kind: Deployment
metadata:
  {{ include "metadata" . | indent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{ include "labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.containername }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerport }}
          