apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  selector:
    {{ include "labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
